### ISSUE TITLE
building a api in flask

### ISSUE THREAD

**Issue by tech-cow** [yuzhoujr/blockmaster#1]
need some help setting up the flask API, step by step tutorial is online or you can write it yourself, I am busy with other project and would want some help on this to complete this mini project

**Comment by saeedanabtawi** [comment]
Sure, i am very happy to help you to build the flask API.

**Comment by tech-cow** [comment]
Thanks Saeedanabtawi.
step by step tutorial is here: https://hackernoon.com/learn-blockchains-by-building-one-117428612f46
You can go ahead on this one!

**Comment by brettvanderwerff** [comment]
I'm new to open source and saw this as a good first issue. Is this still open? I think I need to read a bit more about your program and the tutorial before committing to help on this, but I do have some basic flask experience ad might be able to help.

**Comment by tech-cow** [comment]
@brettvanderwerff , YES, go ahead and do it :)
step by step tutorial is here: https://hackernoon.com/learn-blockchains-by-building-one-117428612f46

**Comment by brettvanderwerff** [comment]
I'm sorry I think I am going to pass on this actually. It looks like it is already completed in the tutorial and on another repo.

**Comment by ghost** [comment]
Hey @yuzhoujr, I am new to open source and I do scripting in python for fun. is this still open? can I work on this?

**Comment by tech-cow** [comment]
@vamsidharBada arBada , sure go ahead

step by step tutorial is here: https://hackernoon.com/learn-blockchains-by-building-one-117428612f46

**Comment by Gaurav-Pande** [comment]
Hi, @yuzhoujr  I would like to contribute to this task. Is this still open?

**Comment by tech-cow** [comment]
@Gaurav-Pande . sure go ahead

step by step tutorial is here: https://hackernoon.com/learn-blockchains-by-building-one-117428612f46
